name: firebase_db_cache
description: A Flutter plugin for fetching Firebase database data with read from
  cache first then server.
version: 1.1.0
homepage: https://github.com/zeshuaro/data_cache_manager/tree/main/firebase_db_cache

environment:
  sdk: "<4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  data_cache_manager: ^1.0.0
  firebase_database: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  mockito: ^5.0.7
  pedantic: ^1.11.0
  sqflite: ^2.0.0+3
  sqflite_common: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_db_cache
      ios:
        default_package: firebase_db_cache
