name: firebase_db_cache
description: A Flutter plugin for fetching Firebase database data with read from
  cache first then server.
version: 0.2.0
homepage: https://github.com/zeshuaro/data_cache_manager/tree/main/firebase_db_cache

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  data_cache_manager: ">=0.0.1 <0.1.0"
  firebase_database: ">=6.0.0 <6.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2
  sqflite: ^1.2.1+3
  sqflite_common: ^1.0.3+1
  sqflite_common_ffi: ^1.1.1+3

flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_db_cache
      ios:
        default_package: firebase_db_cache
