name: data_cache_manager
description: A Flutter cache manager plugin for storing and managing Dart data types.
version: 1.2.0
homepage: https://github.com/zeshuaro/data_cache_manager/tree/main/data_cache_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  copy_with_extension: ^4.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  ntp: ^2.0.0
  path: ^1.8.0
  sqflite: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  copy_with_extension_gen: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mockito: ^5.0.7
  pedantic: ^1.11.0
  sqflite_common: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: data_cache_manager
      ios:
        default_package: data_cache_manager
