name: data_cache_manager
description: A Flutter cache manager plugin for storing and managing Dart data types.
version: 1.0.0+1
homepage: https://github.com/zeshuaro/data_cache_manager/tree/main/data_cache_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: ">=2.0.0 <2.1.0"
  equatable: ">=2.0.0 < 2.1.0"
  json_annotation: ">=4.0.0 <4.1.0"
  ntp: ">=2.0.0 <2.1.0"
  path: ">=1.8.0 <1.9.0"
  sqflite: ">=2.0.0 <2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  copy_with_extension_gen: ^2.0.1
  json_serializable: ^4.1.0
  mockito: ^5.0.7
  pedantic: ^1.11.0
  sqflite_common: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: data_cache_manager
      ios:
        default_package: data_cache_manager
