name: data_cache_manager
description: A Flutter cache manager package for storing and managing Dart data types.
version: 0.0.1
homepage: https://github.com/zeshuaro/data_cache_manager/tree/main/data_cache_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: ">=1.4.0 <1.5.0"
  equatable: ">=1.2.0 < 1.3.0"
  json_annotation: ">=3.1.0 <3.2.0"
  ntp: ">=1.0.0 <1.1.0"
  path: ^1.7.0
  sqflite: ">=1.3.0 <1.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  copy_with_extension_gen: ^1.4.0
  json_serializable: ^3.5.1
  pedantic: ^1.9.2
  sqflite_common: ^1.0.3+1
  sqflite_common_ffi: ^1.1.1+3

flutter:
  plugin:
    platforms:
      android:
        default_package: data_cache_manager
      ios:
        default_package: data_cache_manager
